# Generated by Django 3.2.21 on 2023-10-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('K-Pop', 'K-Pop'), ('Pagode', 'Pagode'), ('Samba', 'Samba'), ('Sertanejo Universitário', 'Sertanejo Universitário'), ('MPB', 'MPB')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Premiacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotif.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('compositor', models.CharField(max_length=50)),
                ('gravadora', models.CharField(max_length=50)),
                ('duracao', models.TimeField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotif.album')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotif.artista')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotif.artista'),
        ),
    ]
