# Generated by Django 3.2.21 on 2023-10-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotif', '0002_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spotif.album'),
        ),
    ]
